apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web
  labels:
    app: staticweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: staticweb
  template:
    metadata:
      labels:
        app: staticweb
    spec:
      containers:
      - name: staticweb
        image: ismailmuhammed/staticweb:v1
        ports:
        - containerPort: 80